# Generated by Django 6.0.5 on 2026-05-10 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_photo', models.ImageField(upload_to='meals/%Y/%m/%d/')),
                ('nutrition_score', models.IntegerField(blank=True, help_text='Auto-calculated nutrition score (0-100)', null=True)),
                ('nutrition_status', models.CharField(blank=True, choices=[('safe', 'Safe'), ('unsafe', 'Unsafe')], max_length=10, null=True)),
                ('protein_content', models.FloatField(blank=True, help_text='Estimated protein in grams', null=True)),
                ('carb_content', models.FloatField(blank=True, help_text='Estimated carbs in grams', null=True)),
                ('fat_content', models.FloatField(blank=True, help_text='Estimated fat in grams', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_records', to='schools.school')),
            ],
            options={
                'db_table': 'meal_records',
                'ordering': ['-date'],
            },
        ),
    ]
